---
name: CI tests
on:
  push:
    branches: ["*"]
jobs:
  run-tests-example-01:
    defaults:
      run:
        working-directory: 01-address-book-no-validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 01-address-book-no-validate/package.json
      - name: Run tests
        run: |
          npm ci
          npm run test:coverage
  run-tests-example-02:
    defaults:
      run:
        working-directory: 02-address-book-manual-validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 02-address-book-manual-validation/package.json
      - name: Run tests
        run: |
          npm ci
          npm run test:coverage
  run-tests-example-03:
    defaults:
      run:
        working-directory: 03-address-book-joi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 03-address-book-joi/package.json
      - name: Run tests
        run: |
          npm ci
          npm run test:coverage
  run-tests-example-04:
    defaults:
      run:
        working-directory: 04-address-book-ts-node
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 04-address-book-ts-node/package.json
      - name: Run tests
        run: |
          npm ci
          npm run test:coverage
